### ISSUE TITLE
Does not create "ejin_like_count" column in the users table

### ISSUE THREAD

**Issue by lukasdeveloper** [johnlewissims/like-counter#1]
Hello,

currently only comments show in your extension and not likes. It looks like it does not create the "ejin_like_count" column in the users table.

Kind Regards

**Comment by johnlewissims** [comment]
Thanks for raising this issue.  The latest release of the extension fixes this problem by removing the column entirely and adding the query to the User Serializer. Update to the latest version and you'll be set.  Let me know if you have anymore issues, otherwise I'll close this in a couple of days.
